name: Test & Tag

on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs:
  UnitTesting:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
      - uses: go test ./...
  Benchmark:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
      - uses: go test -bench=.